[[docs]]
  name = "About Hugo"
  weight = 1
  identifier = "about"
  url = "/en/about/"

[[docs]]
  name = "Getting Started"
  weight = 5
  identifier = "getting-started"
  url = "/en/getting-started/"

[[docs]]
  name = "Hugo Modules"
  weight = 15
  identifier = "modules"
  post = "break"
  url = "/en/hugo-modules/"

# Core Menus

[[docs]]
  name = "Content Management"
  weight = 20
  identifier = "content-management"
  post = "expanded"
  url = "/en/content-management/"

[[docs]]
  name = "Templates"
  weight = 25
  identifier = "templates"

  url = "/en/templates/"

[[docs]]
  name = "Functions"
  weight = 30
  identifier = "functions"
  url = "/en/functions/"

[[docs]]
  name = "Variables"
  weight = 35
  identifier = "variables"
  url = "/en/variables/"
[[docs]]
  name = "Hugo Pipes"
  weight = 36
  identifier = "pipes"
  url = "/en/hugo-pipes/"
[[docs]]
  name = "CLI"
  weight = 40
  post = "break"
  identifier = "commands"
  url = "/en/commands/"



# LOW LEVEL ITEMS


[[docs]]
  name = "Troubleshooting"
  weight = 60
  identifier = "troubleshooting"
  url = "/en/troubleshooting/"

[[docs]]
  name = "Tools"
  weight = 70
  identifier = "tools"
  url = "/en/tools/"

[[docs]]
  name = "Hosting & Deployment"
  weight = 80
  identifier = "hosting-and-deployment"
  url = "/en/hosting-and-deployment/"

[[docs]]
  name = "Contribute"
  weight = 100
  post = "break"
  identifier = "contribute"
  url = "/contribute/"

#[[docs]]
#  name = "Tags"
#  weight = 120
#  identifier = "tags"
#  url = "/tags/"


# [[docs]]
#   name = "Categories"
#   weight = 140
#   identifier = "categories"
#   url = "/categories/"

######## QUICKLINKS

  [[quicklinks]]
    name = "Fundamentals"
    weight = 1
    identifier = "fundamentals"
    url = "/en/tags/fundamentals/"




######## GLOBAL ITEMS TO BE SHARED WITH THE HUGO SITES

[[global]]
    name = "News"
    weight = 1
    identifier = "news"
    url = "/en/news/"

  [[global]]
    name = "Docs"
    weight = 5
    identifier = "docs"
    url = "/en/documentation/"

  [[global]]
    name = "Themes"
    weight = 10
    identifier = "themes"
    url = "https://themes.gohugo.io/"

    [[global]]
      name = "Showcase"
      weight = 20
      identifier = "showcase"
      url = "/en/showcase/"

  # Anything with a weight > 100 gets an external icon
  [[global]]
    name = "Community"
    weight = 150
    icon = true
    identifier = "community"
    post = "external"
    url = "https://discourse.gohugo.io/"


  [[global]]
    name = "GitHub"
    weight = 200
    identifier = "github"
    post = "external"
    url = "https://github.com/gohugoio/hugo"